name: Build
on:
  workflow_run:
    workflows: ['Make pull']
    types:
      - completed

jobs:
  front:
    name: front
    runs-on: ubuntu-latest
    steps:
      - name: Build front
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.IP }}
          username: user
          password: ${{ secrets.PASSWORD }}
          port: 666
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            cd university-front
            npm i
            cp nuxt.config.prod.ts nuxt.config.ts
            pm2 stop index
            npm run build
            cd ./.output/server
            pm2 start index.mjs
